version: '3'

services:
  app:
    command: sh -c "bundle install && rails server -b 0.0.0.0 -p 5000"
    depends_on:
      - pgsql
    image: 
    environment:
      DATABASE_URL: 
    networks:
      - 
    ports:
      - '5000:5000'
    volumes:
      - .:/app

  pgsql:
    build:
      context: .docker/pgsql
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
  redis_data: