version: '3'

services:
  app:
    image: tapp_api:latest 
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: pgsql
    ports:
      - '5000:3000'
    volumes:
      - .:/app
    depends_on:
      - pgsql

  pgsql:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'